import os
import json
import yaml
import pandas as pd
from dotenv import load_dotenv
from datasets import Dataset

from core.llm import GroqEngine
from core.embeddings import EmbeddingEngine
from indexing.manager import IndexManager
from retrieval.query_rewriter import QueryRewriter
from retrieval.reranker import NeuralReranker
from retrieval.hybrid_retriever import HybridRetriever
from utils.logger import get_logger

# RAGAS specific imports
from ragas import evaluate
from ragas.metrics import faithfulness, answer_relevancy, context_precision, context_recall
from langchain_groq import ChatGroq
from langchain_community.embeddings import HuggingFaceEmbeddings

load_dotenv()
logger = get_logger("Ragas_Evaluator")

def load_config():
    with open("config.yaml", "r") as f:
        return yaml.safe_load(f)

def main():
    config = load_config()
    
    logger.info("1. Initializing RAG Pipeline components...")
    # Your internal pipeline models
    internal_llm = GroqEngine(model=config["llm"]["model"])
    embedder = EmbeddingEngine(model_name=config["models"]["embedding"])
    reranker = NeuralReranker(model_name=config["models"]["reranker"])
    
    index_manager = IndexManager(embedder, config["indexing"])
    if not index_manager.load("saved_index"):
        logger.error("Could not load saved_index! Aborting.")
        return
        
    retriever = HybridRetriever(
        index_manager=index_manager, 
        rewriter=QueryRewriter(internal_llm), 
        reranker=reranker, 
        config=config["retrieval"]
    )

    logger.info("2. Loading Testset...")
    with open("evaluation/testset.json", "r") as f:
        testset = json.load(f)

    # Data structures for RAGAS
    questions = []
    ground_truths = []
    answers = []
    contexts = []

    logger.info("3. Running pipeline against test questions (This may take a minute)...")
    for i, item in enumerate(testset):
        q = item["question"]
        gt = item["ground_truth"]
        
        # Run retrieval
        retrieved_chunks = retriever.retrieve(q)
        chunk_texts = [c.text for c in retrieved_chunks]
        
        # Run generation
        context_str = "\n\n".join(chunk_texts)
        prompt = f"Context:\n{context_str}\n\nQuestion: {q}\nAnswer:"
        ans = internal_llm.generate(prompt)
        
        questions.append(q)
        ground_truths.append(gt)
        answers.append(ans)
        contexts.append(chunk_texts)
        
        logger.info(f"Answered {i+1}/{len(testset)}")

    # Format for RAGAS HuggingFace Dataset
    data = {
        "question": questions,
        "answer": answers,
        "contexts": contexts,
        "ground_truth": ground_truths
    }
    dataset = Dataset.from_dict(data)

    logger.info("4. Initializing RAGAS Judges (using Groq & MiniLM)...")
    # RAGAS needs Langchain wrapper objects to function properly
    ragas_llm = ChatGroq(model=config["llm"]["model"], temperature=0.0)
    ragas_embeddings = HuggingFaceEmbeddings(model_name=config["models"]["embedding"])

    logger.info("5. Evaluating! (The LLM Judge is scoring your pipeline)...")
    result = evaluate(
        dataset=dataset,
        metrics=[faithfulness, answer_relevancy, context_precision, context_recall],
        llm=ragas_llm,
        embeddings=ragas_embeddings
    )

    logger.info("\n=== EVALUATION RESULTS ===")
    df = result.to_pandas()
    
    # Safely print the columns that actually exist
    logger.info(f"Columns generated by RAGAS: {df.columns.tolist()}")
    print("\n", df.head(10)) # Just print the top 10 rows safely
    
    # Save results
    os.makedirs("evaluation", exist_ok=True)
    df.to_csv("evaluation/ragas_results.csv", index=False)
    logger.info("✅ Detailed results saved to evaluation/ragas_results.csv")

if __name__ == "__main__":
    main()
    main()